Practical Machine Learning Course Project
========================================================

I decided to use random forests in building my model, and I chose cv, cross-validate, as resampling method, as the default resampling method, bootstrapping, is slow. No preprocessing was used.
 
Cross-validation set was used to estimate the out-of-sample error, which was 0.0098.
 
After removing the columns containing mostly NAs I was able to reduce the variables down to 93, and since I was studying the sensor data I dropped the first 7 columns, getting down to 86 variables. By choosing only the variables containing numeric data, I was able to reduce the variable set down to 53, including the predictable 'classe' variable. So finally I had 52 predictors, which was used to predict the 'classe' variable. 

Test predictions: 20/20

Time to fit model: ~3 minutes


```{r cache = TRUE}
library(caret)
library(doParallel)


set.seed(123)

# Use parallel processing
cl <- makeCluster(4)  # Use 4 cores
registerDoParallel(cl)

# Read the data
pml <- read.csv("pml-training.csv", header=TRUE)
pmltest <- read.csv("pml-testing.csv", header=TRUE)

# Reducing variables from dataset
NAs <- apply(pml,2,function(x) {sum(is.na(x))}) 

validData <- pml[,which(NAs < 19216)]

NAs <- apply(validData,2,function(x) {sum(is.na(x))}) 

sum(NAs) == 0                    # True! No more NAs in validData
length(validData)                # 93
validData <- validData[,8:93]
length(validData)                # 86

vd <- validData[sapply(validData[-86], function(x) is.integer(x) | is.numeric(x))] 
length(vd)                       # 53

# Use the same variables in the test set less 'classe'
a <- names(vd)
c <- pmltest[a[-53]]

# Create training and cross validation sets
trainindex <- createDataPartition(vd$classe, p = 0.5)[[1]]
training <- vd[trainindex,]
crossval <- vd[-trainindex,]

# Take time
ptm <- proc.time()

# Train the model
modFit <- train(classe ~ .,  
                method = "rf",
                trControl = trainControl(method = "cv", number = 4, allowParallel=T), 
                data = training)
# Report time
proc.time() - ptm

modFit

confuse <- confusionMatrix(crossval$classe,predict(modFit,crossval))
confuse

# Out-of-sample error
outofsample <- 1 - confuse$overall['Accuracy'][[1]]
outofsample

d <- predict(modFit, c)
d

```

